### ISSUE TITLE
defaultContent folder is not getting created

### ISSUE THREAD

**Issue by rajankonar90** [ruthvikvegunta/easy_defContentExport#1]
defaultContent folder is not getting created but success message is appeared 
![image](https://user-images.githubusercontent.com/22835707/69705447-9c29dd80-111b-11ea-8d31-4d77b4e914de.png)

**Comment by ruthvikvegunta** [comment]
Fixed!!!, I have changed the way how the script runs, please download the latest version from git and use **--help** argument to get a better understanding of how the script works
